---
- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/web_app.conf
  register: nginx_conf

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started

- name: Restart Nginx if configuration changes
  systemd:
    name: nginx
    state: restarted
  when: nginx_conf.changed
